---
title: "Tables S3. Excess deaths by substance and California Census Region"
author: "Mathew Kiang"
date: "2/9/2022"
output: 
  html_document:
    code_folding: 'hide'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r error=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(kableExtra)
library(knitr)
source(here("code", "utils.R"))

FORECAST_START <- as.Date(config::get("forecast_start"))
LAST_WEEK <- as.Date(config::get("last_week"))

formatC2 <- function(x, ...) {
  formatC(round(x), format = "d", big.mark = ",")
}
```

```{r error=FALSE, message=FALSE, warning=FALSE}
## Data ----
reshaped_pop <- bind_rows(readRDS(here(
  "data", "pop_by_race_educ_extrapolated.RDS"
)) %>%
  mutate(region_name = "California",
         region = 99),
readRDS(here(
  "data", "pop_by_race_region_extrapolated.RDS"
)))

cume_excess_deaths <- bind_rows(
    readRDS(here("data", "cume_excess_deaths.RDS")) %>%
        filter(educ == "all",
               race == "all",
               date == max(date)) %>%
        mutate(region_name = "California",
               region = 99),
    readRDS(here(
        "data", "cume_excess_deaths_region.RDS"
    )) %>%
        filter(educ == "all",
               race == "all",
               date == max(date))
) %>%
    complete(nesting(region, region_name, race, educ, date), death_type) %>%
    filter(
        death_type != "non_covid",
        death_type != "other_opioid",
        death_type != "any_poisoning",
        death_type != "nondrug_poisoning",
        death_type != "unintent_nondrug_poisoning",
        death_type != "intent_nondrug_poisoning"
    ) %>%
    mutate(year = lubridate::year(date)) %>%
    left_join(reshaped_pop) %>%
    categorize_region() %>%
    categorize_race() %>%
    categorize_educ() %>%
    categorize_death()

ca_county <- cume_excess_deaths  %>%
    filter(region != 99,
           death_type != "all_deaths") %>%
    left_join(ca_regions_fips) %>%
    mutate(fips = sprintf("06%03d", county_fips),
           fitted_100k = fitted / pop * 100000)

expected_deaths <- bind_rows(
  readRDS(here("data", "expected_deaths.RDS"))  %>%
        mutate(region_name = "California",
               region = 99),
  readRDS(here("data", "expected_deaths_region.RDS"))
) %>%
    categorize_region() %>%
    categorize_race() %>%
    categorize_educ() %>%
    categorize_death()

super_table <- expected_deaths %>%
  filter(
    between(date, FORECAST_START, LAST_WEEK) |
      between(
        date,
        FORECAST_START - lubridate::years(1),
        LAST_WEEK - lubridate::years(1)
      )
  ) %>%
  mutate(year = lubridate::year(date)) %>%
  group_by(year,
           race,
           race_cat,
           educ,
           educ_cat,
           region,
           region_cat,
           death_type,
           death_cat) %>%
  summarize(
    observed_deaths = sum(outcome),
    expected_deaths = sum(expected),
    mean_pop = mean(population)
  ) %>%
  arrange(race_cat, educ_cat, region_cat, death_cat, year) %>%
  pivot_wider(
    id_cols = c(
      race,
      race_cat,
      educ,
      educ_cat,
      region,
      region_cat,
      death_type,
      death_cat
    ),
    names_from = year,
    values_from = observed_deaths:mean_pop
  ) %>%
    left_join(
        cume_excess_deaths %>%
            filter(date == max(date)) %>%
            select(
                race, 
                race_cat,
                educ, 
                educ_cat,
                region,
                region_cat, 
                death_type,
                death_cat,
                excess_mean = fitted,
                excess_lower = lower,
                excess_upper = upper
            )
    )

super_table <- super_table %>%
    ungroup() %>%
    filter(
        death_type != "all_deaths",
        death_type != "non_covid",
        death_type != "other_opioid",
        death_type != "any_poisoning",
        death_type != "nondrug_poisoning",
        death_type != "unintent_nondrug_poisoning",
        death_type != "intent_nondrug_poisoning",
        !grepl("_alone", death_type, fixed = TRUE),
        death_type != "no_specified_drug",
        death_type != "other_drug"
    ) %>%
    filter(race == "all",
           educ == "all")
```

```{r}
## Absolute numbers
table_1 <- super_table %>%
    filter(educ == "all", race == "all") %>%
    transmute(
        region_cat,
        death_cat,
        obs_exp_2020_deaths = sprintf(
            "%s (%s)",
            formatC2(observed_deaths_2020),
            formatC2(expected_deaths_2020)
        ),
        excess_2020_deaths = sprintf(
            "%s (%s to %s)",
            formatC2(excess_mean),
            formatC2(excess_lower),
            formatC2(excess_upper)
        ),
        excess_per_100k = sprintf(
            "%0.2f (%0.2f to %0.2f)",
            round(excess_mean / mean_pop_2020 * 100000, 2),
            round(excess_lower / mean_pop_2020 * 100000, 2),
            round(excess_upper / mean_pop_2020 * 100000, 2)
        ),
        obs_deaths_2019 = formatC2(observed_deaths_2019),
        ratio_yoy = sprintf("%0.2f", round(
            observed_deaths_2020 / observed_deaths_2019, 2
        ))
    ) 

table_1 %>%
  select(-region_cat) %>%
    kable(
        format = "html",
        col.names = c(
            # "Region",
            "Death type",
            "Observed (expected) deaths in January 5 to December 26, 2020",
            "Excess deaths (95% CI) January 5 to December 26, 2020",
            "Excess deaths (95% CI) per 100,000 population",
            "Observed deaths in January 5 to December 26, 2019",
            "Ratio of observed deaths in 2019 vs 2020"
        ),
        booktabs = TRUE
    ) %>%
    kableExtra::kable_styling(bootstrap = c("striped", "scale_down")) %>%
    kableExtra::pack_rows("All of California", 1, 11) %>%
    kableExtra::pack_rows("(1) Superior California", 12, 16) %>%
    kableExtra::pack_rows("(2) North Coast", 17, 19) %>%
    kableExtra::pack_rows("(3) San Francisco Bay Area", 20, 28) %>%
    kableExtra::pack_rows("(4) Northern San Joaquin Valley", 29, 32) %>%
    kableExtra::pack_rows("(5) Central Coast", 33, 36) %>%
    kableExtra::pack_rows("(6) Southern San Joaquin Valley", 37, 40) %>%
    kableExtra::pack_rows("(7) Inland Empire", 41, 44) %>%
    kableExtra::pack_rows("(8) Los Angeles County", 45, 53) %>%
    kableExtra::pack_rows("(9) Orange County", 54, 59) %>%
    kableExtra::pack_rows("(10) San Diego - Imperial", 60, 64)
  
```
